import {
  CooperativeConfig,
  Member,
  User,
  SavingsTransaction,
  Loan,
  LoanInstallment,
  AuditLog,
  Product,
  SaleTransaction,
  PerjalananDinasRate,
  PerjalananDinas,
  PengawasanNote,
  PenyertaanModal,
  PengeluaranBarang,
} from "@/types";

export const initialPerjalananDinasRates: PerjalananDinasRate[] = [
  {
    tingkat: "DALAM_KECAMATAN",
    label: "Dalam Kecamatan (Bandar Sei Kijang)",
    uangHarian: 150000,
    transport: 75000,
    penginapan: 0,
  },
  {
    tingkat: "DALAM_KABUPATEN",
    label: "Kabupaten Pelalawan (Pangkalan Kerinci)",
    uangHarian: 250000,
    transport: 200000,
    penginapan: 250000,
  },
  {
    tingkat: "LUAR_KABUPATEN_PROVINSI",
    label: "Provinsi Riau (Pekanbaru / Luar Kabupaten)",
    uangHarian: 350000,
    transport: 400000,
    penginapan: 400000,
  },
  {
    tingkat: "LUAR_PROVINSI",
    label: "Luar Provinsi Riau (Jakarta / Nasional)",
    uangHarian: 500000,
    transport: 1500000,
    penginapan: 650000,
  },
];

export const initialConfig: CooperativeConfig = {
  coopName: "Koperasi Desa Merah Putih Lubuk Ogung",
  villageName: "Lubuk Ogung",
  subDistrict: "Bandar Sei Kijang",
  district: "Kabupaten Pelalawan",
  province: "Riau",
  legalNumber: "AHU-0029381.AH.01.26.TAHUN 2026",
  simpananPokokAmount: 100000,
  simpananWajibMonthly: 30000,
  defaultLoanInterestRate: 1.0,
  maxLoanWithoutMasterApproval: 5000000,
  currentFiscalYear: 2026,
  shuEstimateTotal: 48500000,
  martMemberDiscountPercent: 2.5,
  sbmPerjalananDinas: initialPerjalananDinasRates,
};

export const initialUsers: User[] = [
  {
    id: "usr-master-1",
    username: "aidil",
    password: "kopdes2026",
    name: "Aidil Fadilah, S.T",
    role: "MASTER",
    email: "aidil.fadilah@lubukogung.desa.id",
    phone: "0812-7566-0001",
    isActive: true,
    createdAt: "2026-01-01T08:00:00Z",
  },
  {
    id: "usr-pengawas-1",
    username: "pengawas",
    password: "kopdes2026",
    name: "Drs. H. M. Syukri, M.Si",
    role: "PENGAWAS",
    email: "pengawas.syukri@lubukogung.desa.id",
    phone: "0811-7654-3210",
    isActive: true,
    createdAt: "2026-01-01T08:30:00Z",
  },
  {
    id: "usr-manager-1",
    username: "manager",
    password: "kopdes2026",
    name: "Surya Pratama, S.E",
    role: "MANAGER",
    email: "surya.manager@lubukogung.desa.id",
    phone: "0812-9988-7766",
    isActive: true,
    createdAt: "2026-01-01T10:00:00Z",
  },
  {
    id: "usr-admin-1",
    username: "rifaldo",
    password: "kopdes2026",
    name: "Rifaldo Almaghribi, S.T",
    role: "ADMIN",
    email: "rifaldo.almaghribi@lubukogung.desa.id",
    phone: "0813-6477-0002",
    isActive: true,
    createdAt: "2026-01-02T09:00:00Z",
  },
  {
    id: "usr-bendahara-1",
    username: "abil",
    password: "kopdes2026",
    name: "Abil Syahdinu Pradiksa, S.T",
    role: "BENDAHARA",
    email: "abil.syahdinu@lubukogung.desa.id",
    phone: "0821-7188-0003",
    isActive: true,
    createdAt: "2026-01-02T09:30:00Z",
  },
  {
    id: "usr-kasir-1",
    username: "kasir",
    password: "kopdes2026",
    name: "Siti Rahmawati",
    role: "KASIR",
    email: "siti.kasir@lubukogung.desa.id",
    phone: "0822-8399-4455",
    isActive: true,
    createdAt: "2026-01-03T08:00:00Z",
  },
  {
    id: "usr-gudang-1",
    username: "gudang",
    password: "kopdes2026",
    name: "Bambang Irawan",
    role: "GUDANG",
    email: "bambang.gudang@lubukogung.desa.id",
    phone: "0812-7488-5566",
    isActive: true,
    createdAt: "2026-01-03T08:30:00Z",
  },
];

// DATA BERSIH UNTUK PELUNCURAN RESMI (0 DUMP DATA)
export const initialMembers: Member[] = [];
export const initialSavings: SavingsTransaction[] = [];
export const initialLoans: Loan[] = [];
export const initialInstallments: LoanInstallment[] = [];
export const initialSales: SaleTransaction[] = [];
export const initialPerjalananDinas: PerjalananDinas[] = [];
export const initialPengawasanNotes: PengawasanNote[] = [];
export const initialPengeluaranBarang: PengeluaranBarang[] = [];

// PENYERTAAN MODAL AWAL DARI PEMERINTAH / APBDES
export const initialPenyertaanModal: PenyertaanModal[] = [
  {
    id: "pm-001",
    nomorReferensi: "PM-2026/DESA/01",
    sumber: "Pemerintah Desa Lubuk Ogung (APBDes) & Kemendesa PDTT",
    kategori: "PEMERINTAH",
    nominal: 35000000,
    tanggal: "2026-01-02",
    peruntukan: "Modal Awal Pembangunan Koperasi Desa & Pengadaan Sarana Prasarana",
    buktiDokumen: "Perdes Lubuk Ogung No. 02/2026",
    penerima: "Abil Syahdinu Pradiksa, S.T (Bendahara)",
    metode: "TRANSFER_BANK",
    catatan: "Dana penyertaan modal awal pembangunan koperasi desa resmi bersumber dari pemerintah.",
    status: "DITERIMA",
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: "log-launch",
    timestamp: "2026-01-02T08:00:00Z",
    userId: "usr-master-1",
    userName: "Aidil Fadilah, S.T",
    userRole: "MASTER",
    action: "SISTEM_LAUNCH",
    details: "Sistem Koperasi Desa Merah Putih Lubuk Ogung resmi diinisialisasi dalam kondisi data bersih untuk peluncuran resmi.",
  },
];

// KATALOG MASTER PRODUK TOKO KOPDES MART (SIAP DIPERJUALBELIKAN ATAU DIKULAKAN)
export const initialProducts: Product[] = [
  {
    id: "prd-1",
    sku: "SBK-001",
    barcode: "8991001001",
    name: "Beras Premium Solok Anak Daro (Sak 5 Kg)",
    category: "SEMBAKO",
    unit: "sak 5kg",
    costPrice: 72000,
    priceMember: 76000,
    priceGeneral: 80000,
    stock: 0,
    minStock: 5,
    isActive: true,
  },
  {
    id: "prd-2",
    sku: "SBK-002",
    barcode: "8991001002",
    name: "Minyak Goreng Minyakita Pouch 1 Liter",
    category: "SEMBAKO",
    unit: "liter",
    costPrice: 14500,
    priceMember: 15500,
    priceGeneral: 17000,
    stock: 0,
    minStock: 10,
    isActive: true,
  },
  {
    id: "prd-3",
    sku: "SBK-003",
    barcode: "8991001003",
    name: "Gula Pasir Kristal Putih Gulaku 1 Kg",
    category: "SEMBAKO",
    unit: "kg",
    costPrice: 16500,
    priceMember: 17500,
    priceGeneral: 18500,
    stock: 0,
    minStock: 10,
    isActive: true,
  },
  {
    id: "prd-4",
    sku: "SBK-004",
    barcode: "8991001004",
    name: "Tepung Terigu Segitiga Biru 1 Kg",
    category: "SEMBAKO",
    unit: "kg",
    costPrice: 11000,
    priceMember: 12000,
    priceGeneral: 13000,
    stock: 0,
    minStock: 8,
    isActive: true,
  },
  {
    id: "prd-5",
    sku: "SBK-005",
    barcode: "8991001005",
    name: "Telur Ayam Ras Segar (Papan isi 30 butir)",
    category: "SEMBAKO",
    unit: "papan",
    costPrice: 48000,
    priceMember: 51000,
    priceGeneral: 54000,
    stock: 0,
    minStock: 5,
    isActive: true,
  },
  {
    id: "prd-6",
    sku: "DPR-001",
    barcode: "8991002001",
    name: "Indomie Goreng Spesial (Dus isi 40 pcs)",
    category: "DAPUR",
    unit: "dus",
    costPrice: 112000,
    priceMember: 118000,
    priceGeneral: 124000,
    stock: 0,
    minStock: 5,
    isActive: true,
  },
  {
    id: "prd-7",
    sku: "DPR-002",
    barcode: "8991002002",
    name: "Kopi Kapal Api Spesial Mix 1 Renceng (10 sachet)",
    category: "DAPUR",
    unit: "renceng",
    costPrice: 12500,
    priceMember: 14000,
    priceGeneral: 15000,
    stock: 0,
    minStock: 5,
    isActive: true,
  },
  {
    id: "prd-8",
    sku: "DPR-003",
    barcode: "8991002003",
    name: "Teh Celup Sariwangi Kotak (Isi 25)",
    category: "DAPUR",
    unit: "kotak",
    costPrice: 6500,
    priceMember: 7500,
    priceGeneral: 8500,
    stock: 0,
    minStock: 5,
    isActive: true,
  },
  {
    id: "prd-9",
    sku: "MND-001",
    barcode: "8991003001",
    name: "Deterjen Daia Putih / Bunga 850g",
    category: "MANDI_CUCI",
    unit: "bungkus",
    costPrice: 17500,
    priceMember: 19000,
    priceGeneral: 20500,
    stock: 0,
    minStock: 5,
    isActive: true,
  },
  {
    id: "prd-10",
    sku: "MND-002",
    barcode: "8991003002",
    name: "Sabun Mandi Lifebuoy Total 10 (Isi 4 Batang)",
    category: "MANDI_CUCI",
    unit: "pack",
    costPrice: 14000,
    priceMember: 16000,
    priceGeneral: 18000,
    stock: 0,
    minStock: 5,
    isActive: true,
  },
  {
    id: "prd-11",
    sku: "MNM-001",
    barcode: "8991004001",
    name: "Air Mineral Aqua Galon 19 Liter (Isi Ulang Resmi)",
    category: "MINUMAN",
    unit: "galon",
    costPrice: 18000,
    priceMember: 20000,
    priceGeneral: 22000,
    stock: 0,
    minStock: 5,
    isActive: true,
  },
  {
    id: "prd-12",
    sku: "PRT-001",
    barcode: "8991006001",
    name: "Pupuk NPK Mutiara 16-16-16 Repack 1 Kg",
    category: "PERTANIAN",
    unit: "kg",
    costPrice: 16000,
    priceMember: 17500,
    priceGeneral: 19000,
    stock: 0,
    minStock: 5,
    isActive: true,
  },
];
